image: node:10.16.3
options:
  max-time: 30
pipelines:
   pull-requests:
      '**':
        - step:
            script:
                - apt-get update
                - apt-get install zip
                - npm install --unsafe-perm
                - npm run test
                - npm run autotest:prod